CREATE TABLE grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso VARCHAR(30) NOT NULL,
    seccion VARCHAR(5) NOT NULL,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    CONSTRAINT uk_grupos_curso_seccion UNIQUE (curso, seccion)
);

CREATE TABLE profesores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(9) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    email VARCHAR(150)
);

CREATE TABLE franjas_horarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL UNIQUE CHECK (numero BETWEEN 1 AND 6),
    nombre VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE alumnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(9) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    email VARCHAR(150),
    grupo_id BIGINT NOT NULL REFERENCES grupos(id)
);

CREATE TABLE permisos_bano (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    profesor_id BIGINT NOT NULL REFERENCES profesores(id),
    franja_horaria_id BIGINT NOT NULL REFERENCES franjas_horarias(id),
    fecha DATE NOT NULL,
    hora TIME WITHOUT TIME ZONE NOT NULL,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios_app (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    contrasena_hash VARCHAR(100) NOT NULL,
    perfil VARCHAR(30) NOT NULL CHECK (perfil IN ('GESTION_PERMISOS', 'GESTION_CATALOGOS')),
    profesor_id BIGINT NOT NULL UNIQUE REFERENCES profesores(id)
);

INSERT INTO grupos (curso, seccion, codigo)
VALUES
    ('1º ESO', 'A', '1ºA ESO'), ('1º ESO', 'B', '1ºB ESO'),
    ('2º ESO', 'A', '2ºA ESO'), ('2º ESO', 'B', '2ºB ESO'),
    ('3º ESO', 'A', '3ºA ESO'), ('3º ESO', 'B', '3ºB ESO'),
    ('4º ESO', 'A', '4ºA ESO'), ('4º ESO', 'B', '4ºB ESO'),
    ('1º Bachillerato', 'A', '1ºA Bachillerato'), ('1º Bachillerato', 'B', '1ºB Bachillerato'),
    ('2º Bachillerato', 'A', '2ºA Bachillerato'), ('2º Bachillerato', 'B', '2ºB Bachillerato');

INSERT INTO franjas_horarias (numero, nombre)
VALUES
    (1, '1º Hora'), (2, '2º Hora'), (3, '3º Hora'),
    (4, '4º Hora'), (5, '5º Hora'), (6, '6º Hora');

INSERT INTO profesores (dni, nombre, apellidos, email)
VALUES ('00000001A', 'Profesor', 'Inicial', 'profesor.inicial@example.test');
