DROP TABLE IF EXISTS permisos_bano;
DROP TABLE IF EXISTS alumnos;
DROP TABLE IF EXISTS profesores;
DROP TABLE IF EXISTS franjas_horarias;
DROP TABLE IF EXISTS grupos;

CREATE TABLE grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso VARCHAR(30) NOT NULL,
    seccion VARCHAR(5) NOT NULL,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    CONSTRAINT uk_grupos_curso_seccion UNIQUE (curso, seccion)
);

CREATE TABLE profesores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(9) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    email VARCHAR(150)
);

CREATE TABLE franjas_horarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL UNIQUE CHECK (numero BETWEEN 1 AND 6),
    nombre VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE alumnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(9) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    email VARCHAR(150),
    grupo_id BIGINT NOT NULL REFERENCES grupos(id)
);

CREATE TABLE permisos_bano (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    profesor_id BIGINT NOT NULL REFERENCES profesores(id),
    franja_horaria_id BIGINT NOT NULL REFERENCES franjas_horarias(id),
    fecha DATE NOT NULL,
    hora TIME WITHOUT TIME ZONE NOT NULL,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO grupos (curso, seccion, codigo)
VALUES
    ('1º ESO', 'A', '1ºA ESO'), ('1º ESO', 'B', '1ºB ESO'),
    ('2º ESO', 'A', '2ºA ESO'), ('2º ESO', 'B', '2ºB ESO'),
    ('3º ESO', 'A', '3ºA ESO'), ('3º ESO', 'B', '3ºB ESO'),
    ('4º ESO', 'A', '4ºA ESO'), ('4º ESO', 'B', '4ºB ESO'),
    ('1º Bachillerato', 'A', '1ºA Bachillerato'), ('1º Bachillerato', 'B', '1ºB Bachillerato'),
    ('2º Bachillerato', 'A', '2ºA Bachillerato'), ('2º Bachillerato', 'B', '2ºB Bachillerato');

INSERT INTO franjas_horarias (numero, nombre)
VALUES
    (1, '1º Hora'), (2, '2º Hora'), (3, '3º Hora'),
    (4, '4º Hora'), (5, '5º Hora'), (6, '6º Hora');

INSERT INTO profesores (dni, nombre, apellidos, email)
VALUES
    ('00000001A', 'Marta', 'López', 'marta.lopez@example.test'),
    ('00000002B', 'Javier', 'Sánchez', 'javier.sanchez@example.test'),
    ('00000003C', 'Elena', 'Ruiz', 'elena.ruiz@example.test'),
    ('00000004D', 'Carlos', 'Martín', 'carlos.martin@example.test'),
    ('00000005E', 'Ana', 'Torres', 'ana.torres@example.test'),
    ('00000006F', 'Pedro', 'Gómez', 'pedro.gomez@example.test');

INSERT INTO alumnos (dni, nombre, apellidos, email, grupo_id)
SELECT datos.dni, datos.nombre, datos.apellidos, datos.email, grupos.id
FROM (VALUES
    ('00000011A', 'Lucía', 'Fernández', 'lucia.fernandez@example.test', '1ºA ESO'),
    ('00000012B', 'Hugo', 'Martínez', 'hugo.martinez@example.test', '1ºA ESO'),
    ('00000013C', 'Sofía', 'Rodríguez', 'sofia.rodriguez@example.test', '2ºB ESO'),
    ('00000014D', 'Daniel', 'García', 'daniel.garcia@example.test', '3ºA ESO'),
    ('00000015E', 'Paula', 'Sánchez', 'paula.sanchez@example.test', '4ºB ESO'),
    ('00000016F', 'Mateo', 'Pérez', 'mateo.perez@example.test', '1ºB Bachillerato'),
    ('00000017G', 'Emma', 'Díaz', 'emma.diaz@example.test', '1ºB ESO'),
    ('00000018H', 'Leo', 'Romero', 'leo.romero@example.test', '2ºA ESO'),
    ('00000019J', 'Valeria', 'Navarro', 'valeria.navarro@example.test', '2ºB ESO'),
    ('00000020K', 'Adrián', 'Ortega', 'adrian.ortega@example.test', '3ºB ESO'),
    ('00000021L', 'Carmen', 'Molina', 'carmen.molina@example.test', '4ºA ESO'),
    ('00000022M', 'Mario', 'Castro', 'mario.castro@example.test', '2ºA Bachillerato')
) AS datos(dni, nombre, apellidos, email, codigo_grupo)
JOIN grupos ON grupos.codigo = datos.codigo_grupo;

INSERT INTO permisos_bano (alumno_id, profesor_id, franja_horaria_id, fecha, hora)
SELECT alumnos.id, profesores.id, franjas_horarias.id, CURRENT_DATE, datos.hora::time
FROM (VALUES
    ('Lucía', 'Fernández', 'Marta', 'López', 1, '08:35:00'),
    ('Hugo', 'Martínez', 'Marta', 'López', 2, '09:25:00'),
    ('Sofía', 'Rodríguez', 'Javier', 'Sánchez', 3, '10:20:00'),
    ('Daniel', 'García', 'Elena', 'Ruiz', 4, '11:40:00'),
    ('Paula', 'Sánchez', 'Carlos', 'Martín', 5, '12:30:00'),
    ('Mateo', 'Pérez', 'Ana', 'Torres', 6, '13:20:00')
) AS datos(alumno_nombre, alumno_apellidos, profesor_nombre, profesor_apellidos, numero_franja, hora)
JOIN alumnos ON alumnos.nombre = datos.alumno_nombre AND alumnos.apellidos = datos.alumno_apellidos
JOIN profesores ON profesores.nombre = datos.profesor_nombre AND profesores.apellidos = datos.profesor_apellidos
JOIN franjas_horarias ON franjas_horarias.numero = datos.numero_franja;
